### ISSUE TITLE
NullPointerException on using repeated field for JSON body template in HTTP sink

### ISSUE THREAD

**Issue by prakharmathur82** [odpf/firehose#156]
## 🐛 Bug Report
For HTTP Sink JSON Templatised body, if there is a repeated field being used for JSON body creation, then firehose silently fails with NullPointerException while reporting metrics

```
java.lang.NullPointerException: null
	at java.time.Duration.between(Duration.java:473)
	at io.odpf.firehose.metrics.StatsDReporter.captureDurationSince(StatsDReporter.java:53)
	at io.odpf.firehose.metrics.Instrumentation.captureSinkExecutionTelemetry(Instrumentation.java:165)
	at io.odpf.firehose.sink.AbstractSink.pushMessage(AbstractSink.java:56)
	at io.odpf.firehose.sinkdecorator.SinkDecorator.pushMessage(SinkDecorator.java:28)
```

## Expected Behavior
Firehose should throw proper errors for non-supported field types

## Steps to Reproduce
Steps to reproduce the behavior.
1. Use an input proto having repeated field
2. Use that repeated field in JSON body template
3. Run firehose

**Comment by lavkesh** [comment]
It's happening in the prepare method, the exception is not handled properly.

**Comment by prakharmathur82** [comment]
It is happening for normal HTTP sink as well, if you leave extra spaces in the service url
